substitutions:
  # names
  name: "aquapi"
  friendly_name: "AquaPi"

  # App Version - Updated: 8/2023
  appVersion: "0.1c"

  # pins
  sdaPin: "21"
  sclPin: "22"
  
  # EZO Circuit Addresses
  # PMP circuit, who's address is 103
  addPMP: "103"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  # Automatically add the mac address to the name
  name_add_mac_suffix: true
  project:
    name: TheRealFalseReality.aquapi
    version: "${appVersion}"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: verbose

# Enable Home Assistant API
api:

ota:

wifi:
  ap:

captive_portal:

web_server:

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none
  
improv_serial:

# i2c Pins
i2c:
  sda: ${sdaPin}
  scl: ${sclPin}
  scan: true
  id: bus_a

# Internal Blue LED
light:
  - platform: status_led
    # name: "Internal LED"
    pin: GPIO2
    id: internal_led
    # entity_category: "Config"

sensor:
  # EZO Circuit - EC
  # Conductivity
  - platform: ezo
    icon: mdi:shaker-outline
    name: "Conductivity"
    id: pmp_ezo
    address: 102
    unit_of_measurement: ""
    accuracy_decimals: 2
    update_interval: 2s
    state_class: "measurement"

button:
  # Calibrate the temp probe to 146.2
  - platform: template
    name: "PMP - Calibration - 146.2"
    id: pmp_cal_100
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            id(pmp_ezo).send_custom("cal,146.2");

  # Perform Calibration CLEAR
  - platform: template
    name: "PMP - Calibration Clear"
    id: pmp_cal_clear
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            id(pmp_ezo).clear_calibration();

  # Perform Calibration Check
  - platform: template
    name: "PMP - Calibration - check"
    id: pmp_cal_check
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            id(pmp_ezo).get_calibration();

  # Perform Status Check
  - platform: template
    name: "PMP - Staus Check"
    id: pmp_status
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            id(pmp_ezo).send_custom("Status");

  # Get Device Firmware Version
  - platform: template
    name: "PMP - Get Information"
    id: pmp_info
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            id(pmp_ezo).get_device_information();

  # Manual Read
  - platform: template
    name: "PMP - Manual Read"
    id: pmp_read
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            id(pmp_ezo).get_state();