substitutions:
  # names
  name: "aquaponics-kit"
  friendly_name: "Aquaponics Kit"

  # App Version - Updated: 6/2023
  app_version: "2026.6"

  # EZO Circuit Addresses
  # pH circuit, who's address is 99
  addPH: "99"
  # EC circuit, who's address is 100
  addEC: "100"
  # DO circuit, who's address is 97
  addDO: "97"
  # RTD circuit, who's address is 102
  addRTD: "102"
  # PMP circuit, who's address is 103
  addPMP: "103"
  # HUM circuit, who's address is 111
  addHUM: "111"
  # CO2 circuit, who's address is 105
  addCO2: "105"

packages:
  device_base: !include common/device_base.yaml
  aquaponics: !include common/aquaponics.yaml
  ezo_ph: !include common/ezo_ph.yaml
  ezo_ec: !include common/ezo_ec.yaml
  # ezo_orp: !include common/ezo_orp.yaml
  ezo_hum: !include common/ezo_hum.yaml
  ezo_rtd: !include common/ezo_rtd.yaml
  ezo_co2: !include common/ezo_co2.yaml
  # ezo_do: !include common/ezo_do.yaml
  ezo_pmp: !include common/ezo_pmp.yaml
  # debug: !include common/debug.yaml
  # ezo_commands: !include common/ezo_commands.yaml