substitutions:
  # names
  name: "aquaponics-kit"
  friendly_name: "Aquaponics Kit"

  # App Version - Updated: 6/2023
  app_version: "24.11.1"

  # EZO Circuit Addresses
  # pH circuit, who's address is 99
  addPH: "99"
  # EC circuit, who's address is 100
  addEC: "100"
  # DO circuit, who's address is 97
  addDO: "97"
  # RTD circuit, who's address is 102
  addRTD: "102"
  # PMP circuit, who's address is 103
  addPMP: "103"
  # HUM circuit, who's address is 111
  addHUM: "111"
  # CO2 circuit, who's address is 105
  addCO2: "105"

packages:
  aquaponics: !include common/aquaponics.yaml
  TheRealFalseReality.device_base: github://TheRealFalseReality/aquapi/common/device_base.yaml
  TheRealFalseReality.ph: github://TheRealFalseReality/aquapi/common/ezo_ph.yaml
  TheRealFalseReality.ec: github://TheRealFalseReality/aquapi/common/ezo_ec.yaml
  # TheRealFalseReality.orp: github://TheRealFalseReality/aquapi/common/ezo_orp.yaml
  TheRealFalseReality.hum: github://TheRealFalseReality/aquapi/common/ezo_hum.yaml
  TheRealFalseReality.rtd: github://TheRealFalseReality/aquapi/common/ezo_rtd.yaml
  TheRealFalseReality.c02: github://TheRealFalseReality/aquapi/common/ezo_co2.yaml
  # TheRealFalseReality.do: github://TheRealFalseReality/aquapi/common/ezo_do.yaml
  TheRealFalseReality.pmp: github://TheRealFalseReality/aquapi/common/ezo_pmp.yaml
  # TheRealFalseReality.debug: github://TheRealFalseReality/aquapi/common/debug.yaml
  # TheRealFalseReality.commands: github://TheRealFalseReality/aquapi/common/ezo_commands.yaml
