substitutions:
  # names
  name: "hydroponics-kit"
  friendly_name: "Hydroponics Kit"
  comment: "Hydroponics Kit for ESPHome"
  project_name: "therealfalsereality.hydroponics_kit"
  firmware_manifest_url: "https://therealfalsereality.github.io/Aquaponics_Pool_Kit-AtlasScientific/firmware/hydroponics-kit.manifest.json"
  firmware_ota_url: "https://therealfalsereality.github.io/Aquaponics_Pool_Kit-AtlasScientific/firmware/hydroponics-kit-esp32.ota.bin"
  firmware_md5_url: "https://therealfalsereality.github.io/Aquaponics_Pool_Kit-AtlasScientific/firmware/hydroponics-kit-esp32.ota.bin.md5"
  import: "false"

dashboard_import:
  package_import_url: github://TheRealFalseReality/Aquaponics_Pool_Kit-AtlasScientific/hydroponics_kit.yaml
  import_full_config: "${import}"

packages:
  TheRealFalseReality.device_base: github://TheRealFalseReality/aquapi/common/device_base.yaml
  TheRealFalseReality.app_version: github://TheRealFalseReality/aquapi/common/aquapi_app_version.yaml
  TheRealFalseReality.ph: github://TheRealFalseReality/aquapi/common/ezo_ph.yaml
  TheRealFalseReality.ec: github://TheRealFalseReality/aquapi/common/ezo_ec.yaml
  # TheRealFalseReality.hum: github://TheRealFalseReality/aquapi/common/ezo_hum.yaml
  TheRealFalseReality.rtd: github://TheRealFalseReality/aquapi/common/ezo_rtd.yaml
  # TheRealFalseReality.c02: github://TheRealFalseReality/aquapi/common/ezo_co2.yaml
  TheRealFalseReality.pmp: github://TheRealFalseReality/aquapi/common/ezo_pmp.yaml
  TheRealFalseReality.water_quality: github://TheRealFalseReality/aquapi/common/water_quality.yaml
  # TheRealFalseReality.debug: github://TheRealFalseReality/aquapi/common/debug.yaml
  # TheRealFalseReality.commands: github://TheRealFalseReality/aquapi/common/ezo_commands.yaml
  # TheRealFalseReality.do: github://TheRealFalseReality/aquapi/common/ezo_do.yaml
  TheRealFalseReality.orp: github://TheRealFalseReality/aquapi/common/ezo_orp.yaml
  #  TheRealFalseReality.i2c_detection: github://TheRealFalseReality/aquapi/common/i2c_detection.yaml
  esp32_saola_1: !include common/espboard.yaml
  TFT_st7789v: !include common/TFT_st7789v.yaml