substitutions:
  # names
  name: "pool-kit"
  friendly_name: "Pool Kit"
  comment: "Pool Kit for ESP32"
  project_name: "therealfalsereality.pool-kit"
  firmware_manifest_url: "https://therealfalsereality.github.io/Aquaponics_Pool_Kit-AtlasScientific/firmware/pool-kit.manifest.json"
  firmware_ota_url: "https://therealfalsereality.github.io/Aquaponics_Pool_Kit-AtlasScientific/firmware/pool-kit-esp32.ota.bin"
  firmware_md5_url: "https://therealfalsereality.github.io/Aquaponics_Pool_Kit-AtlasScientific/firmware/pool-kit-esp32.ota.bin.md5"
  update_pmp_green: "never"
  update_pmp_red: "never"

packages:
  TheRealFalseReality.device_base: github://TheRealFalseReality/aquapi/common/device_base.yaml
  TheRealFalseReality.app_version: github://TheRealFalseReality/aquapi/common/aquapi_app_version.yaml
  TheRealFalseReality.ph: github://TheRealFalseReality/aquapi/common/ezo_ph.yaml
  TheRealFalseReality.rtd: github://TheRealFalseReality/aquapi/common/ezo_rtd.yaml
  TheRealFalseReality.do: github://TheRealFalseReality/aquapi/common/ezo_do.yaml
  TheRealFalseReality.orp: github://TheRealFalseReality/aquapi/common/ezo_orp.yaml
  TheRealFalseReality.pmp: github://TheRealFalseReality/aquapi/common/ezo_pmp.yaml
#   TheRealFalseReality.water_quality: github://TheRealFalseReality/aquapi/common/water_quality.yaml
  TheRealFalseReality.water_quality: 
    url: https://github.com/TheRealFalseReality/aquapi
    ref: main
    file: common/water_quality.yaml
    refresh: 1s
  # TheRealFalseReality.debug: github://TheRealFalseReality/aquapi/common/debug.yaml
  # TheRealFalseReality.commands: github://TheRealFalseReality/aquapi/common/ezo_commands.yaml
  # TheRealFalseReality.i2c_detection: github://TheRealFalseReality/aquapi/common/i2c_detection.yaml
  esp32-saola-1: !include common/espboard.yaml
  TFT_st7789v: !include common/TFT_st7789v.yaml
  pool: !include common/pool.yaml
