substitutions:
  # names
  name: "pool-kit"
  friendly_name: "Pool Kit"
  comment: "Pool Kit for ESP32"
  project_name: "therealfalsereality.pool-kit"
  firmware_manifest_url: "https://therealfalsereality.github.io/Aquaponics_Pool_Kit-AtlasScientific/firmware/pool-kit.manifest.json"
  firmware_ota_url: "https://therealfalsereality.github.io/Aquaponics_Pool_Kit-AtlasScientific/firmware/pool-kit-esp32.ota.bin"
  firmware_md5_url: "https://therealfalsereality.github.io/Aquaponics_Pool_Kit-AtlasScientific/firmware/pool-kit-esp32.ota.bin.md5"

packages:
#   TheRealFalseReality.device_base: github://TheRealFalseReality/aquapi/common/device_base.yaml
  TheRealFalseReality.ph: github://TheRealFalseReality/aquapi/common/ezo_ph.yaml
  TheRealFalseReality.rtd: github://TheRealFalseReality/aquapi/common/ezo_rtd.yaml
  # TheRealFalseReality.debug: github://TheRealFalseReality/aquapi/common/debug.yaml
  # TheRealFalseReality.commands: github://TheRealFalseReality/aquapi/common/ezo_commands.yaml
  TheRealFalseReality.do: github://TheRealFalseReality/aquapi/common/ezo_do.yaml
  TheRealFalseReality.orp: github://TheRealFalseReality/aquapi/common/ezo_orp.yaml
  TheRealFalseReality.pmp: github://TheRealFalseReality/aquapi/common/ezo_pmp.yaml
  device_base: !include common/device_base.yaml
  pool: !include common/pool.yaml

light:
  - id: !remove internal_led