substitutions:
  # App Version
  app_version: "26.6.0"

text_sensor:
  # GitHub Project URL
  - platform: template
    name: GitHub
    id: github
    icon: mdi:github
    lambda: |-
      return {"https://github.com/TheRealFalseReality/Aquaponics_Pool_Kit-AtlasScientific"};
    entity_category: "diagnostic"

binary_sensor:
  -  id: !extend ezo_rtd_detected
     disabled_by_default: false
  -  id: !extend ezo_ec_detected
     disabled_by_default: true
  -  id: !extend ezo_pmp_red_detected
     disabled_by_default: true
  -  id: !extend ezo_pmp_green_detected
     disabled_by_default: true