substitutions:
  # App Version
  app_version: "26.6.1"

text_sensor:
  # GitHub Project URL
  - id: !extend github
    lambda: |-
      return {"https://github.com/TheRealFalseReality/Aquaponics_Pool_Kit-AtlasScientific"};
    
  - id: !remove hardware_variant_sensor
