substitutions:
  # names
  name: "aquaponics-kit"
  friendly_name: "Aquaponics Kit"
  comment: "Aquaponics Kit for ESP32"
  project_name: "therealfalsereality.aquaponics_kit"

  # I2C pins - Adafruit HUZZAH32 – ESP32 Feather Board
  sdaPin: "23" # yellow/TX
  # EZO Circuit Addresses
  # pH circuit, who's address is 99
  addPH: "99"
  # EC circuit, who's address is 100
  addEC: "100"
  # DO circuit, who's address is 97
  addDO: "97"
  # RTD circuit, who's address is 102
  addRTD: "102"
  # PMP circuit, who's address is 103
  addPMP: "103"
  # HUM circuit, who's address is 111
  addHUM: "111"
  # CO2 circuit, who's address is 105
  addCO2: "105"

dashboard_import:
  package_import_url: github://TheRealFalseReality/Aquaponics-Kit/aquaponics-kit.yaml
  import_full_config: "${import}"

text_sensor: 
  # AquaPi Version
  - platform: template
    name: "Version"
    id: aquaponics_version
    icon: mdi:update
    update_interval: 600s
    lambda: |-
      return {"${app_version}"};
    entity_category: "diagnostic"

  # GitHub Project URL
  - platform: template
    name: GitHub
    id: github
    icon: mdi:github
    lambda: |-
      return {"github.com/TheRealFalseReality/Aquaponics-Kit"};
    entity_category: "diagnostic"
