substitutions:
  sorting_group_misc_weight: '97'
  sorting_group_diagnostic_weight: '98'
  sorting_group_config_weight: '99'
  import: "false"

esphome:
  min_version: 2024.6.0
  name: "${name}"
  friendly_name: "${friendly_name}"
  # Automatically add the mac address to the name
  name_add_mac_suffix: true
  comment: "Aquaonics Kit for ESP32"
  project:
    name: therealfalsereality.aquapi
    version: "${app_version}"

dashboard_import:
  package_import_url: github://TheRealFalseReality/Aquaponics-Kit/aquaponics-kit.yaml
  import_full_config: "${import}"

web_server:
  version: 3
  sorting_groups:
    - id: sorting_group_diagnostic
      name: "Aquaonics Kit Diagnostic"
      sorting_weight: ${sorting_group_diagnostic_weight}
    - id: sorting_group_config
      name: "Aquaonics Kit Configuration"
      sorting_weight: ${sorting_group_config_weight}
    - id: sorting_group_misc
      name: "Misc. Sensors"
      sorting_weight: ${sorting_group_misc_weight}

text_sensor: 
  # AquaPi Version
  - platform: template
    name: "Version"
    id: aquaponics_version
    icon: mdi:update
    update_interval: 600s
    lambda: |-
      return {"${app_version}"};
    entity_category: "diagnostic"

  # GitHub Project URL
  - platform: template
    name: GitHub
    id: github
    icon: mdi:github
    lambda: |-
      return {"github.com/TheRealFalseReality/Aquaponics-Kit"};
    entity_category: "diagnostic"