substitutions:
  import: "false"

  # I2C pins - Adafruit HUZZAH32 – ESP32 Feather Board
  sdaPin: "42" # yellow/TX
  sclPin: "41" # green/RX

  addPMP_white: "109"  # EZO PMP-L

packages:
  aquapi_app_version: !include app_version.yaml

dashboard_import:
  package_import_url: github://TheRealFalseReality/Aquaponics_Pool_Kit-AtlasScientific/pool-kit.yaml
  import_full_config: "${import}"

  # GitHub Project URL
  - platform: template
    name: GitHub
    id: github
    icon: mdi:github
    lambda: |-
      return {"https://github.com/TheRealFalseReality/Aquaponics_Pool_Kit-AtlasScientific"};
    entity_category: "diagnostic"
