substitutions:
  import: "false"

  # I2C pins - Adafruit HUZZAH32 – ESP32 Feather Board
  sdaPin: "42"
  sclPin: "41"

  addPMP_whit1e: "109"  # EZO PMP-L

dashboard_import:
  package_import_url: github://TheRealFalseReality/Aquaponics_Pool_Kit-AtlasScientific/pool_kit.yaml
  import_full_config: "${import}"

esp32:
  board: esp32-s2-saola-1