# CHANGEME: Set these variable to your liking
title: ESPHome Atlas Scientific Wifi Aquaponics Kit
description: Powered by ESPHome and ESP Web Tools and made for HomeAssistant
theme: jekyll-theme-modernist
