name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: esphome/workflows/.github/workflows/publish.yml@dependabot/github_actions/esphome/build-action-3.1.0
    with:
      # CHANGEME: Set the filenames of your config files here:
      files: aquaponics-kit.yaml
      # CHANGEME: Set the name of your project here:
      name: Atlas Scientific Wifi Aquaponics Kit
